#dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

language: node_js
node_js:
  - "7"

os: 
 - linux
 # - osx

dist: xenial

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

install:
  
  - git config --global user.name "kanna12"
  - git config --global user.email "kgoku98@gmail.com"
  - npm install
  - npm install -g electron electron-packager electron-builder
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  - sudo dpkg --add-architecture i386
  # - wget -nc https://dl.winehq.org/wine-builds/winehq.key && sudo apt-key add winehq.key && sudo apt update -y
  - wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt install aptitude
  - sudo aptitude install winehq-stable
  # - wget https://dl.winehq.org/wine/source/4.0/wine-4.0.tar.xz
  # - tar -xvf wine-4.0.tar.xz
  # - cd wine-4.0/
  # - sudo ./configure 
  # # - sudo ./configure --enable-win64
  # - sudo make && sudo make install
  # - sudo apt-get install wine
  - wine --version
  
script:
  - npm run pack-win
  - pwd
  - ls -ltr .

  
# deploy:
  # provider: releases
  # file: "archive.zip"
  # api_key: $semantic # Set in the settings page of your repository, as a secure variable
  # on:
  # repo: Kanna12/Semantic-version
  # skip_cleanup: true
  # all_branches: true
  # overwrite: true
 
