#dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

# language: node_js
# node_js:
  # - "7"
os: 
 - linux
 - osx
 - windows  
# before_install:
# - brew install git-lfs

# before_script:
# - git lfs pull

script:
  - echo $TRAVIS_OS_NAME
  - if: os=linux
    echo " hello i am linux"
# install:
  
  # - git config --global user.name "kanna12"
  # - git config --global user.email "kgoku98@gmail.com"
  # - npm install
  # - npm install -g electron electron-packager electron-builder
# script:
  # - npm run dist
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]] || [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pwd; ls -ltr .; zip -r archive.zip ./dist; fi
  # - if: os = windows 
    # jar -cMf archive.zip 
  
# deploy:
  # provider: releases
  # file: "archive.zip"
  # api_key: $semantic # Set in the settings page of your repository, as a secure variable
  # keep-history: true
  
  # on:
  # repo: Kanna12/Semantic-version
  # skip_cleanup: true
  # all_branches: true
  # tags: true
 

  # trying new things
#deploy:
# new
 #  provider: npm 
  # email: "kgoku98@gmail.com"
   #api_key: "4bcf2159-1f36-4313-a03b-26c3a07fc1f7"
    
   # github-token: $GITHUB_TOKEN
   # file: "release-build"
    #skip_cleanup: true
    #on:
     #tags: true
     #branch: master
 
#- echo "Unit Tests"
#new line added 
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run yarn test; else yarn test; fi

#- echo "E2E Tests"
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xvfb-run yarn test:electron; else yarn test:electron; fi

#- echo "Deploy linux version to GitHub"
#- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn release:linux; fi

#- echo "Deploy windows version to GitHub"
#- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn release:win; fi
#SHSJOPSKK#
#- echo "Deploy mac version to GitHub"
#- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dist release:mac; fi
#I like you 
#before_cache:
 # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -rf $HOME/.cache/electron-builder/wine; fi
#    - npm run 
# new line added 